version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro   # <-- важливо
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/project/staticfiles
      - media_volume:/app/project/media
    working_dir: /app/project
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy                  # <-- чекати, поки MySQL готовий
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/project/staticfiles
      - media_volume:/app/project/media
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

volumes:
  static_volume:
  media_volume:
  db_data: