version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/project/staticfiles
      - media_volume:/app/project/media
    working_dir: /app/project
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    # Видаляємо залежність від локальної БД
    restart: always

  # Видаляємо локальну БД, оскільки використовуєте Railway
  # db:
  #   image: mysql:8.0
  #   ...

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/project/staticfiles
      - media_volume:/app/project/media
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

volumes:
  # mysql_data:  # Видаляємо
  static_volume:
  media_volume: