# Generated by Django 5.2.4 on 2025-07-25 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_request_approved_student_theme'),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='catalog.request'),
        ),
    ]
