# Generated by Django 4.2.18 on 2025-04-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
