# Generated by Django 4.2.18 on 2025-03-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='academic_group',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
    ]
