# Generated by Django 4.2.18 on 2025-03-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_academic_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='academic_group',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
