# Generated by Django 4.2.3 on 2025-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default-avatar.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
