# Generated by Django 5.1.4 on 2025-03-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_patronymic_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default-avatar.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]