# Generated by Django 4.2.18 on 2025-03-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_academic_group_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='По-батькові'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default-avatar.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('Сенсорної та напівпровідникової електроніки', 'Сенсорної та напівпровідникової електроніки'), ('Системного проектування', 'Системного проектування'), ('Фізичної та біомедичної електроніки', 'Фізичної та біомедичної електроніки'), ("Радіофізики та комп'ютерних технологій", "Радіофізики та комп'ютерних технологій"), ("Радіоелектронних і комп'ютерних систем", "Радіоелектронних і комп'ютерних систем"), ('Оптоелектроніки та інформаційних технологій', 'Оптоелектроніки та інформаційних технологій')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
