# Generated by Django 4.2.18 on 2025-03-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_patronymic_customuser_profile_picture_and_more'),
        ('users', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
    ]
