# Generated by Django 4.2.18 on 2025-03-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_profile_picture'),
        ('users', '0004_customuser_patronymic_customuser_profile_picture_and_more'),
    ]

    operations = [
    ]
