# Generated by Django 5.2.4 on 2025-07-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_clear_default_avatar_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='academic_group',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
