# Generated by Django 5.2.4 on 2025-09-21 16:50

from django.db import migrations


def migrate_department_data(apps, schema_editor):
    """
    Переносить дані з CustomUser.department в OnlyTeacher.department
    """
    CustomUser = apps.get_model('users', 'CustomUser')
    OnlyTeacher = apps.get_model('catalog', 'OnlyTeacher')
    Department = apps.get_model('catalog', 'Department')
    Faculty = apps.get_model('catalog', 'Faculty')
    
    print("🔄 Початок міграції даних кафедр...")
    
    # Створюємо Department об'єкти для всіх унікальних кафедр
    department_mapping = {}
    unique_departments = CustomUser.objects.filter(
        role='Викладач', 
        department__isnull=False
    ).values_list('department', flat=True).distinct()
    
    print(f"📋 Знайдено {len(unique_departments)} унікальних кафедр")
    
    # Отримуємо перший факультет як fallback
    fallback_faculty = Faculty.objects.first()
    if not fallback_faculty:
        print("❌ Помилка: Не знайдено жодного факультету!")
        return
    
    for dept_name in unique_departments:
        if dept_name and dept_name.strip():
            # Знаходимо або створюємо Department
            dept_obj, created = Department.objects.get_or_create(
                department_name=dept_name,
                defaults={'faculty': fallback_faculty}
            )
            department_mapping[dept_name] = dept_obj
            if created:
                print(f"✅ Створено нову кафедру: {dept_name}")
            else:
                print(f"📌 Використано існуючу кафедру: {dept_name}")
    
    # Оновлюємо OnlyTeacher профілі
    updated_count = 0
    for user in CustomUser.objects.filter(role='Викладач'):
        if user.department and user.department in department_mapping:
            try:
                teacher_profile = OnlyTeacher.objects.get(teacher_id=user)
                teacher_profile.department = department_mapping[user.department]
                teacher_profile.save()
                updated_count += 1
                print(f"🔄 Оновлено профіль викладача: {user.email}")
            except OnlyTeacher.DoesNotExist:
                print(f"⚠️ Не знайдено профіль для викладача: {user.email}")
    
    print(f"✅ Міграція завершена! Оновлено {updated_count} профілів викладачів")


def reverse_migrate_department_data(apps, schema_editor):
    """
    Зворотна міграція (для відкату)
    """
    CustomUser = apps.get_model('users', 'CustomUser')
    OnlyTeacher = apps.get_model('catalog', 'OnlyTeacher')
    
    print("🔄 Відкат міграції даних кафедр...")
    
    updated_count = 0
    for teacher in OnlyTeacher.objects.filter(department__isnull=False):
        if teacher.teacher_id.department != teacher.department.department_name:
            teacher.teacher_id.department = teacher.department.department_name
            teacher.teacher_id.save()
            updated_count += 1
            print(f"🔄 Відкат профілю викладача: {teacher.teacher_id.email}")
    
    print(f"✅ Відкат завершено! Оновлено {updated_count} профілів викладачів")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_academic_group'),
        ('catalog', '0035_populate_initial_data'),  # Залежність від каталогу
    ]

    operations = [
        migrations.RunPython(migrate_department_data, reverse_migrate_department_data),
    ]
