# Generated by Django 5.2.4 on 2025-09-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_migrate_department_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
    ]
