# Generated by Django 5.2.6 on 2025-09-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_department_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExcelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='По-батькові')),
                ('department', models.CharField(max_length=200, verbose_name='Кафедра')),
                ('group', models.CharField(max_length=50, verbose_name='Група')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Мапінг студентів Excel',
                'verbose_name_plural': 'Мапінги студентів Excel',
                'unique_together': {('last_name', 'first_name', 'patronymic', 'group')},
            },
        ),
        migrations.CreateModel(
            name='StudentRequestMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_email', models.EmailField(max_length=254, verbose_name='Email викладача')),
                ('stream', models.CharField(max_length=50, verbose_name='Потік')),
                ('theme', models.CharField(max_length=500, verbose_name='Тема')),
                ('theme_description', models.TextField(blank=True, verbose_name='Опис теми')),
                ('student_name', models.CharField(max_length=200, verbose_name='Студент')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Мапінг запитів студентів',
                'verbose_name_plural': 'Мапінги запитів студентів',
                'unique_together': {('teacher_email', 'stream', 'student_name')},
            },
        ),
    ]
