# Generated by Django 4.2.18 on 2025-01-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='faculty',
            new_name='department',
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
