# Generated by Django 4.2.18 on 2025-02-21 11:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlyTeacher',
            fields=[
                ('teacher_id', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(max_length=100)),
                ('stream_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('theme_description', models.TextField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.onlyteacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('student_id', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('occupied', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stream_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.stream')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.onlyteacher')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation_text', models.TextField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.CharField(choices=[('pending', 'очікується'), ('accepted', 'прийнятий'), ('rejected', 'відхилений')], default='pending', max_length=100)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.slot')),
                ('student_id', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_themes', models.ManyToManyField(blank=True, to='catalog.studenttheme')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.onlyteacher')),
                ('teacher_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.teachertheme')),
            ],
        ),
    ]
