# Generated by Django 4.2.18 on 2025-02-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='teacher_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.teachertheme'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='stream_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.stream'),
        ),
    ]
