# Generated by Django 4.2.18 on 2025-01-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(max_length=100)),
                ('stream_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='only_teacher',
            name='phone_num',
        ),
        migrations.RemoveField(
            model_name='only_teacher',
            name='sci_interests',
        ),
        migrations.RemoveField(
            model_name='only_teacher',
            name='slots',
        ),
        migrations.CreateModel(
            name='slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.IntegerField()),
                ('occupied', models.IntegerField()),
                ('stream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.stream')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.only_teacher')),
            ],
        ),
    ]
