# Generated by Django 5.1.4 on 2025-07-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='motivation_text',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
