# Generated by Django 4.2.18 on 2025-03-18 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_request_rejected_reason_alter_request_teacher_theme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlyStudent',
            fields=[
                ('student_id', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalog_student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('speciality', models.CharField(max_length=100)),
                ('course', models.IntegerField()),
                ('additional_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='onlyteacher',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='onlyteacher',
            name='position',
        ),
        migrations.AddField(
            model_name='onlyteacher',
            name='academic_level',
            field=models.CharField(choices=[('Асистент', 'Асистент'), ('Доцент', 'Доцент'), ('Професор', 'Професор')], default='Асистент', max_length=50),
        ),
        migrations.AddField(
            model_name='onlyteacher',
            name='additional_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='onlyteacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='academic_year',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='request',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlyteacher',
            name='teacher_id',
            field=models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalog_teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.CharField(choices=[('pending', 'очікується'), ('accepted', 'прийнятий'), ('rejected', 'відхилений'), ('completed', 'завершений')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='student_id',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='users_student_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
