# Generated by Django 4.2.18 on 2025-01-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_stream_remove_only_teacher_phone_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='only_teacher',
            name='department',
            field=models.CharField(blank=True, default='null', max_length=100),
        ),
    ]
