# Generated by Django 5.1.4 on 2025-07-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_request_motivation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='send_contacts',
            field=models.BooleanField(default=False),
        ),
    ]
