# Generated by Django 4.2.18 on 2025-03-26 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_onlystudent_remove_onlyteacher_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.slot'),
        ),
        migrations.AlterField(
            model_name='studenttheme',
            name='student_id',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='users_student_themes', to=settings.AUTH_USER_MODEL),
        ),
    ]
