# Generated by Django 4.2.18 on 2025-01-27 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_only_teacher_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Only_teacher',
            new_name='OnlyTeacher',
        ),
        migrations.RenameModel(
            old_name='slots',
            new_name='Slot',
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
