# Generated by Django 5.2.1 on 2025-07-20 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_request_comment_request_send_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='student_themes',
        ),
        migrations.AddField(
            model_name='studenttheme',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_themes', to='catalog.request'),
            preserve_default=False,
        ),
    ]
