# Generated by Django 4.2.18 on 2025-01-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_only_teacher_onlyteacher_rename_slots_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlyteacher',
            name='department',
        ),
    ]
