# Generated by Django 4.2.18 on 2025-04-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_onlystudent_academic_group_and_more'),
        ('catalog', '0004_alter_request_slot_alter_studenttheme_student_id'),
    ]

    operations = [
    ]
