# Generated by Django 5.2.1 on 2025-07-20 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_request_student_themes_studenttheme_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved_student_theme',
            field=models.ForeignKey(blank=True, help_text='Затверджена студентська тема для цього запиту (якщо обрано тему студента)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='catalog.studenttheme'),
        ),
    ]
