# Generated by Django 4.2.18 on 2025-01-30 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_remove_onlyteacher_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_text',
            new_name='motivation_text',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='theme',
            new_name='student_themes',
        ),
        migrations.AlterField(
            model_name='request',
            name='student_id',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='teacher_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.onlyteacher'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='occupied',
            field=models.IntegerField(default=0),
        ),
    ]
