# Generated by Django 4.2.18 on 2025-04-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_merge_20250404_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.CharField(choices=[('Очікує', 'Очікує'), ('Активний', 'Активний'), ('Відхилено', 'Відхилено'), ('Завершено', 'Завершено')], default='Очікує', max_length=100),
        ),
    ]
