# Generated by Django 5.1.4 on 2025-07-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_request_approved_student_theme'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('teacher_id', 'stream_id'), name='unique_teacher_stream'),
        ),
    ]
