# Generated by Django 5.2.4 on 2025-07-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_request_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='edu_degree',
            field=models.CharField(choices=[('Бакалавр', 'Бакалавр'), ('Магістр', 'Магістр')], max_length=50, null=True),
        ),
    ]
