# Generated by Django 4.2.18 on 2025-02-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_request_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.onlyteacher'),
        ),
    ]
