# Generated by Django 5.2.4 on 2025-07-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_stream_edu_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='work_type',
            field=models.CharField(choices=[('Курсова робота', 'Курсова робота'), ('Дипломна робота', 'Дипломна робота'), ('Магістерська робота', 'Магістерська робота')], default='Курсова робота', help_text='Тип роботи, яку студент планує виконувати', max_length=50),
        ),
    ]
