# Generated by Django 4.2.18 on 2025-02-05 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_request_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='proposed_theme_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.teachertheme'),
        ),
    ]
