# Generated by Django 5.2.4 on 2025-07-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_request_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='work_type',
            field=models.CharField(choices=[('Курсова', 'Курсова'), ('Дипломна', 'Дипломна'), ('Магістерська', 'Магістерська')], default='Курсова', help_text='Тип роботи, яку студент планує виконувати', max_length=50),
        ),
    ]
