# Generated by Django 5.2.4 on 2025-08-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_request_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='custom_student_theme',
            field=models.CharField(blank=True, help_text='Тема, яку студент запропонував самостійно (не з бази тем викладача)', max_length=255, null=True, verbose_name='Довільна тема студента'),
        ),
    ]
