# Generated by Django 4.2.18 on 2025-02-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_request_student_themes_studenttheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttheme',
            name='request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.request'),
        ),
    ]
