# Generated by Django 4.2.18 on 2025-02-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_studenttheme_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttheme',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.request'),
        ),
    ]
