# Generated by Django 5.2.4 on 2025-08-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_request_custom_student_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='custom_student_theme',
            field=models.CharField(blank=True, help_text='Довільна тема студента (для введення в адмінці)', max_length=200, null=True),
        ),
    ]
