# Generated by Django 5.2.4 on 2025-08-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_request_custom_student_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='edu_degree',
        ),
    ]
