# Generated by Django 4.2.18 on 2025-02-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_studenttheme_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlyteacher',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
