# Generated by Django 4.2.18 on 2025-02-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_onlyteacher_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_date',
            new_name='request_time',
        ),
    ]
