# Generated by Django 5.2.4 on 2025-08-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_stream_edu_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlystudent',
            name='education_level',
            field=models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('master', 'Master')], max_length=50, null=True),
        ),
    ]
