# Generated by Django 5.2.4 on 2025-08-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_stream_edu_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertheme',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Позначає, чи тема була видалена (неактивна)'),
        ),
    ]
