# Generated by Django 5.2.4 on 2025-08-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_onlystudent_education_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachertheme',
            options={'ordering': ['teacher_id__teacher_id__last_name', 'theme'], 'verbose_name': 'Тема викладача', 'verbose_name_plural': 'Теми викладачів'},
        ),
        migrations.AddField(
            model_name='teachertheme',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teachertheme',
            name='streams',
            field=models.ManyToManyField(blank=True, related_name='teacher_themes', to='catalog.stream'),
        ),
    ]
