# Generated by Django 4.2.18 on 2025-02-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_rename_request_date_request_request_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_time',
            new_name='request_date_time',
        ),
    ]
