# Generated by Django 4.2.18 on 2025-02-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_rename_request_time_request_request_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
