# Generated by Django 5.2.4 on 2025-08-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_teachertheme_is_deleted'),
        ('catalog', '0016_add_teacher_theme_crud_fields'),
    ]

    operations = [
    ]
