# Generated by Django 5.2.4 on 2025-08-16 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_merge_20250816_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_topic_locked',
            field=models.BooleanField(default=False, verbose_name='Тема затверджена і заблокована'),
        ),
        migrations.AddField(
            model_name='request',
            name='topic_description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис теми'),
        ),
        migrations.AddField(
            model_name='request',
            name='topic_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва теми'),
        ),
        migrations.AlterField(
            model_name='request',
            name='approved_student_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='catalog.studenttheme', verbose_name='Затверджена тема студента'),
        ),
        migrations.AlterField(
            model_name='request',
            name='custom_student_theme',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Довільна тема студента'),
        ),
        migrations.AlterField(
            model_name='request',
            name='teacher_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='catalog.teachertheme', verbose_name='Тема викладача'),
        ),
        migrations.AlterField(
            model_name='teachertheme',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='catalog.onlyteacher'),
        ),
        migrations.AlterField(
            model_name='teachertheme',
            name='theme_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
