# Generated by Django 5.2.4 on 2025-08-16 18:12

from django.db import migrations

def migrate_themes_to_text(apps, schema_editor):
    Request = apps.get_model('catalog', 'Request')
    
    for request in Request.objects.all():
        # Визначаємо джерело теми та зберігаємо в нове текстове поле
        if request.teacher_theme:
            request.topic_name = request.teacher_theme.theme
            request.topic_description = request.teacher_theme.theme_description
        elif request.approved_student_theme:
            request.topic_name = request.approved_student_theme.theme
        elif request.custom_student_theme:
            request.topic_name = request.custom_student_theme
            
        # Встановлюємо блокування для затверджених тем
        if request.request_status in ['Активний', 'Завершено']:
            request.is_topic_locked = True
            
        request.save()

def reverse_migrate_themes(apps, schema_editor):
    # Якщо потрібно відкотити міграцію, залишаємо старі поля без змін
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_request_is_topic_locked_request_topic_description_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_themes_to_text, reverse_migrate_themes),
    ]
