# Generated by Django 5.2.4 on 2025-08-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_migrate_themes_to_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachertheme',
            options={'ordering': ['teacher_id__teacher_id__last_name', 'theme']},
        ),
    ]
