# Generated by Django 5.2.4 on 2025-08-21 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_teachertheme_options'),
        ('users', '0006_alter_customuser_academic_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва факультету')),
                ('code', models.CharField(help_text='Наприклад: ФЕС, ФЕП, ФЕЛ, ФЕІ, ФЕМ', max_length=10, unique=True, verbose_name='Код факультету')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультети',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stream',
            name='year_of_entry',
            field=models.IntegerField(default=2020, help_text='Рік, коли потік почав навчання', verbose_name='Рік вступу'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='specialty_name',
            field=models.CharField(blank=True, help_text='Застаріле поле, буде видалено після міграції', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(help_text='Наприклад: ІМ-21, ПМ-31', max_length=50, unique=True, verbose_name='Код групи')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='catalog.stream', verbose_name='Потік')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
                'ordering': ['group_code'],
            },
        ),
        migrations.CreateModel(
            name='OnlyStudentNew',
            fields=[
                ('student_id', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalog_student_profile_new', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('additional_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Додатковий email')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='catalog.group', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Студент (нова структура)',
                'verbose_name_plural': 'Студенти (нова структура)',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва спеціальності')),
                ('code', models.CharField(help_text='Наприклад: 121, 122, 123', max_length=20, verbose_name='Код спеціальності')),
                ('education_level', models.CharField(choices=[('bachelor', 'Бакалавр'), ('master', 'Магістр'), ('phd', 'Доктор філософії')], max_length=50, verbose_name='Рівень освіти')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='catalog.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Спеціальність',
                'verbose_name_plural': 'Спеціальності',
                'ordering': ['faculty', 'name'],
                'unique_together': {('code', 'faculty', 'education_level')},
            },
        ),
        migrations.AddField(
            model_name='stream',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='catalog.specialty', verbose_name='Спеціальність'),
        ),
    ]
