# Generated by Django 5.2.4 on 2025-08-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_rename_onlystudentnew_to_onlystudent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlystudent',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенти'},
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='code',
        ),
    ]
