# Generated by Django 5.1.4 on 2025-08-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_fix_master_programs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlyteacher",
            name="academic_level",
            field=models.CharField(default="Викладач", max_length=50),
        ),
        migrations.AlterField(
            model_name="onlyteacher",
            name="profile_link",
            field=models.URLField(
                blank=True,
                help_text="Посилання на профіль на сторінці факультету",
                null=True,
                verbose_name="Посилання на профіль",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        help_text="Наприклад: Кафедра комп'ютерних наук",
                        max_length=200,
                        unique=True,
                        verbose_name="Назва кафедри",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="catalog.faculty",
                        verbose_name="Факультет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кафедра",
                "verbose_name_plural": "Кафедри",
                "ordering": ["department_name"],
            },
        ),
        migrations.AddField(
            model_name="onlyteacher",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.department",
                verbose_name="Кафедра",
            ),
        ),
    ]
