# Generated by Django 5.2.4 on 2025-08-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_onlyteacher_academic_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfile',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Збережено в архіві'),
        ),
    ]
