# Generated by Django 5.1.4 on 2025-09-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0030_requestfile_is_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Назва оголошення"),
                ),
                ("content", models.TextField(verbose_name="Текст оголошення")),
                (
                    "author_type",
                    models.CharField(
                        choices=[("faculty", "Факультет"), ("department", "Кафедра")],
                        max_length=20,
                        verbose_name="Тип автора",
                    ),
                ),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("primary", "Основне"),
                            ("warning", "Попередження"),
                            ("success", "Успішне"),
                        ],
                        default="primary",
                        max_length=20,
                        verbose_name="Тип оголошення",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активне"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "author_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="catalog.department",
                        verbose_name="Кафедра",
                    ),
                ),
                (
                    "author_faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="catalog.faculty",
                        verbose_name="Факультет",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
