# Generated by Django 5.1.4 on 2025-09-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0031_announcement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Оголошення",
                "verbose_name_plural": "Оголошення",
            },
        ),
        migrations.AlterModelOptions(
            name="onlyteacher",
            options={"verbose_name": "Викладач", "verbose_name_plural": "Викладачі"},
        ),
        migrations.AlterModelOptions(
            name="request",
            options={"verbose_name": "Запит", "verbose_name_plural": "Запити"},
        ),
        migrations.AlterModelOptions(
            name="slot",
            options={"verbose_name": "Місце", "verbose_name_plural": "Місця"},
        ),
        migrations.AlterModelOptions(
            name="stream",
            options={"verbose_name": "Потік", "verbose_name_plural": "Потоки"},
        ),
        migrations.AlterModelOptions(
            name="teachertheme",
            options={
                "ordering": ["teacher_id__teacher_id__last_name", "theme"],
                "verbose_name": "Тема викладача",
                "verbose_name_plural": "Теми викладачів",
            },
        ),
        migrations.RemoveField(
            model_name="stream",
            name="year_of_entry",
        ),
        migrations.AddField(
            model_name="stream",
            name="work_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Назва роботи"
            ),
        ),
    ]
