# Generated by Django 5.1.4 on 2025-09-12 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0032_alter_announcement_options_alter_onlyteacher_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="onlystudent",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.department",
                verbose_name="Кафедра",
            ),
        ),
    ]
