# Generated by Django 5.2.5 on 2025-09-15 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_alter_announcement_options_alter_onlyteacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Формат: 2024/25', max_length=7, verbose_name='Навчальний рік')),
                ('semestr', models.IntegerField(choices=[(1, '1 семестр'), (2, '2 семестр')], verbose_name='Семестр')),
                ('lock_student_requests_date', models.DateField(blank=True, null=True, verbose_name='Дата блокування подачі запитів студентами')),
                ('student_requests_locked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('lock_teacher_editing_themes_date', models.DateField(blank=True, null=True, verbose_name='Дата блокування редагування тем викладачами')),
                ('teacher_editing_locked_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Редагування тем заблоковано о')),
                ('lock_cancel_requests_date', models.DateField(blank=True, null=True, verbose_name='Дата блокування скасування запитів викладачами')),
                ('allow_complete_work_date', models.DateField(blank=True, null=True, verbose_name='Дата дозволу завершення робіт')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.department', verbose_name='Кафедра')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('department', 'academic_year', 'semestr'), name='uniq_department_year_sem')],
            },
        ),
    ]
