# Generated by Django 5.2.4 on 2025-09-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_onlystudent_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.filecomment'),
        ),
    ]
