# Generated by Django 5.2.5 on 2025-09-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_semestr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semestr',
            options={'ordering': ['-academic_year', 'department', 'semestr'], 'verbose_name': 'Семестр', 'verbose_name_plural': 'Семестри'},
        ),
        migrations.AlterField(
            model_name='semestr',
            name='allow_complete_work_date',
            field=models.DateField(blank=True, help_text='Починаючи з цієї дати дозволено завершувати роботи та виставляти оцінки.', null=True, verbose_name='Дата дозволу завершення робіт'),
        ),
        migrations.AlterField(
            model_name='semestr',
            name='lock_cancel_requests_date',
            field=models.DateField(blank=True, help_text='Після настання цієї дати скасування активних робіт буде заборонено.', null=True, verbose_name='Дата блокування скасування запитів викладачами'),
        ),
        migrations.AlterField(
            model_name='semestr',
            name='lock_student_requests_date',
            field=models.DateField(blank=True, help_text='Після настання цієї дати застосуйте дію для відхилення запитів зі статусом «Очікує».', null=True, verbose_name='Дата блокування подачі запитів студентами'),
        ),
        migrations.AlterField(
            model_name='semestr',
            name='lock_teacher_editing_themes_date',
            field=models.DateField(blank=True, help_text='Після настання цієї дати застосуйте дію для блокування редагування тем (is_topic_locked=True).', null=True, verbose_name='Дата блокування редагування тем викладачами'),
        ),
        migrations.AlterField(
            model_name='semestr',
            name='student_requests_locked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Запити заблоковано о'),
        ),
    ]
