# Generated by Django 5.2.4 on 2025-09-28 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_populate_initial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlystudent',
            name='student_id',
            field=models.OneToOneField(limit_choices_to={'role': 'Студент'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalog_student_profile_new', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='onlyteacher',
            name='teacher_id',
            field=models.OneToOneField(limit_choices_to={'role': 'Викладач'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalog_teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studenttheme',
            name='student_id',
            field=models.ForeignKey(limit_choices_to={'role': 'Студент'}, on_delete=django.db.models.deletion.CASCADE, related_name='users_student_themes', to=settings.AUTH_USER_MODEL),
        ),
    ]
