# Generated by Django 5.2.6 on 2025-09-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_alter_semestr_options_and_more'),
        ('catalog', '0036_alter_onlystudent_student_id_and_more'),
    ]

    operations = [
    ]
