# Generated by Django 5.2.6 on 2025-09-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_alter_onlystudent_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachertheme',
            name='theme',
            field=models.CharField(max_length=200),
        ),
    ]
