# Generated by Django 5.2.6 on 2025-10-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_alter_teachertheme_theme'),
        ('catalog', '0038_create_current_semestr'),
    ]

    operations = [
    ]
