# Generated by Django 5.2.6 on 2025-10-01 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_create_current_semestr'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlystudent',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.faculty', verbose_name='Факультет'),
        ),
    ]
