# Generated by Django 5.2.6 on 2025-10-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_onlystudent_faculty'),
        ('catalog', '0041_clean_and_set_departments'),
    ]

    operations = [
    ]
