# Generated by Django 5.1.4 on 2025-10-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0042_merge_20251002_1902"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="Наприклад: СП, КОІТ",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Коротка назва",
            ),
        ),
    ]
