# Generated by Django 5.1.4 on 2025-10-03 17:37

from django.db import migrations

def populate_short_name(apps, schema_editor):
    Department = apps.get_model('catalog', 'Department')
    
    # Map department_name -> short_name
    short_names = {
        "Сенсорної та напівпровідникової електроніки": "СНПЕ",
        "Системного проектування": "СП",
        "Фізичної та біомедичної електроніки": "ФБМЕ",
        "Радіофізики та комп'ютерних технологій": "РКТ",
        "Радіоелектронних і комп'ютерних систем": "РКС",
        "Оптоелектроніки та інформаційних технологій": "КОІТ",
    }

    for dept_name, short in short_names.items():
        try:
            dept = Department.objects.get(department_name=dept_name)
            dept.short_name = short
            dept.save()
        except Department.DoesNotExist:
            pass  # skip if not found


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0043_department_short_name"),
    ]

    operations = [migrations.RunPython(populate_short_name),]
